version: '3.8'

services:
  # Jaeger - OTelテレメトリの収集と可視化
  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686"  # Jaeger UI
      - "6831:6831/udp"  # Jaeger UDP 
      - "14268:14268"    # Jaeger HTTP
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug

  # BuildKit - OTel対応のビルダー
  buildkitd:
    image: moby/buildkit:v0.13.0
    privileged: true
    ports:
      - "1234:1234"  # BuildKit API
    environment:
      - JAEGER_TRACE=jaeger:6831
      - BUILDKITD_FLAGS=--oci-worker-no-process-sandbox
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
    volumes:
      - buildkit-cache:/var/lib/buildkit
      - ./buildkitd.toml:/etc/buildkitd.toml
    command: --config /etc/buildkitd.toml
    depends_on:
      - jaeger

volumes:
  buildkit-cache: